config/routes.rb
Rails.application.routes.draw do
  root "users#index"
  resources :players
  resources :users, only: [:index, :create]
  resources :sessions, only: [:create]

  get "log_out" => "sessions#destroy"
end

app/models/player.rb
class Player < ActiveRecord::Base
  validates :first_name, :last_name, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :name, :email, presence: true
  validates :email, format: { with: VALID_EMAIL_REGEX }, uniqueness: { :case_sensitive => false }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    User.find(session[:user_id]) if session[:user_id]
  end

  def require_login
    unless session[:user_id]
      flash[:errors] = ["You must login first"]
      redirect_to root_path
    end
  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_action :require_login
  
  def index
    @players = Player.all
  end

  def new
    @player = Player.new
  end

  def create
    player = Player.new(player_params)
    if player.save
      redirect_to :root
    else
      flash[:errors] = player.errors.full_messages
      redirect_to :back
    end
  end

  def show
    @player = Player.find(params[:id])
  end

  def edit
    @player = Player.find(params[:id])
  end

  def update
    player = Player.find(params[:id])
    if player.update(player_params)
      redirect_to :root
    else
      flash[:errors] = player.errors.full_messages
      redirect_to :back
    end
  end

  def destroy
    player = Player.find(params[:id])
    player.destroy
    redirect_to :root
  end

private
  def player_params
    params.require(:player).permit(:first_name, :last_name)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to players_path
    else
      flash[:errors] = ["Invalid Combination"]
      redirect_to :back
    end
  end

  def destroy
    reset_session
    redirect_to :root
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @user = User.new
  end

  def create
    user = User.new(user_params)
    if user.save
      session[:user_id] = user.id
      redirect_to players_path
    else
      flash[:errors] = user.errors.full_messages
      redirect_to :back
    end
  end

private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
	<%= yield %>
</div>

</body>
</html>

app/views/players/_form.html.erb
<% if flash[:errors] %>
	<% flash[:errors].each do |e| %>
		<p><%= e %></p>
	<% end %>
<% end %>

<%= form_for(@player) do |f| %>
	<p>
		<%= f.label :first_name %>
		<%= f.text_field :first_name %>
	</p>
	<p>
		<%= f.label :last_name %>
		<%= f.text_field :last_name %>
	</p>
	<%= f.submit %>
<% end %>	

app/views/players/edit.html.erb
<% content_for(:title, "Edit #{@player.first_name}") %>

<h1>Edit <%= @player.first_name %>'s information</h1>

<%= render partial: "players/form" %>

<%= link_to "Home Page", root_path %>

app/views/players/index.html.erb
<% content_for(:title, "Players") %>

<h1>Listing <%= pluralize(@players.length, "player") %></h1>

<table>
	<thead>
		<tr>
			<td>First Name</td>
			<td>Last Name</td>
			<td>Actions</td>
		</tr>
	</thead>

	<tbody>
		<% @players.each do |player| %>
		<tr>
			<td><%= player.first_name %></td>
			<td><%= player.last_name %></td>
			<td>
				<%= link_to "Show Profile", player_path(player.id) %> |
				<%= link_to "Edit Profile", edit_player_path(player.id) %> |
				<%= link_to "Delete Profile", player_path(player.id), data: { method: :delete, confirm: "Are you sure?" } %>
			</td>
		</tr>
		<% end %>
	</tbody>
</table>

<%= link_to "New Player", new_player_path %> | <%= link_to "Log Out", "/log_out" %>

app/views/players/new.html.erb
<% content_for(:title, "Create Player") %>

<h1>Create a new player</h1>

<%= render partial: "players/form" %>

app/views/players/show.html.erb
<% content_for(:title, "#{@player.first_name}'s Profile") %>

<h1>This is the profile page for <%= @player.first_name %></h1>

<table>
	<thead>
		<tr>
			<td>First Name</td>
			<td>Last Name</td>
		</tr>
	</thead>
	<tbody>
		<tr>
			<td><%= @player.first_name %></td>
			<td><%= @player.last_name %></td>
		</tr>
	</tbody>
</table>

<%= link_to "Home Page", root_path %>

app/views/users/index.html.erb
<% if flash[:errors] %>
	<div class="row">
		<% flash[:errors].each do |e| %>
			<p class="text-danger"><%= e %></p>
		<% end %>	
	</div>
<% end %>

<div class="row">
	<div id="registration" class="col-md-6">
		<h1>Register</h1>
		<%= form_for @user do |f| %>
			<div class="form-group">
				<%= f.label :name %>:
				<%= f.text_field :name %>
			</div>
			<div class="form-group">
				<%= f.label :email %>:
				<%= f.email_field :email %>
			</div>	
			<div class="form-group">
				<%= f.label :password %>:
				<%= f.password_field :password %>
			</div>	
			<div class="form-group">
				<%= f.label :password_confirmation %>:
				<%= f.password_field :password_confirmation %>
			</div>		
			<%= f.submit %>	
		<% end %>
	</div>

	<div id="login" class="col-md-6">
		<h1>Login</h1>
		<%= form_tag sessions_path do %>
			<div class="form-group">
				<%= label_tag :email %>:
				<%= email_field_tag :email %>
			</div>	
			<div class="form-group">
				<%= label_tag :password %>:
				<%= password_field_tag :password %>
			</div>
			<%= submit_tag "Sign In" %>
		<% end %>				
	</div>
</div>